# Grand Passage
# CC
#DATA_DIR = "/home/razoumov/scratch/mguerra"
#OUTPUT_DIR = "/home/svassili/scratch/Visualization/energy3/frames"
# Laptop
DATA_DIR = "/Users/svassili/ACENET/Visualization/energy3/vtu"
OUTPUT_DIR = "/Users/svassili/ACENET/Visualization/energy3/tmp"
SAVE_ANIMATION = False
ANIMATION_FILE = "Grand.png"
COLOR_MAP = 'jet'
BACKGROUND = [0.0, 0.1, 0.05]
CAMERA_POSITION = [-141900, 277300, 380000]
CAMERA_FOCAL_POINT = [-141900, 277300, 0]
CAMERA_PARALLEL_SCALE = 2500
CAMERA_ROLL = -90
GLYPH_MODE = 'Every Nth Point'
GLYPH_STRIDE = 1000
GLYPH_SCALE_FACTOR = 150.0
GLYPH_VECTOR_SCALE_MODE = 'Scale by Components'
GLYPH2_MODE = 'Uniform Spatial Distribution (Surface Sampling)'
#GLYPH2_MODE = None
GLYPH2_SCALE_FACTOR = 150.0
GLYPH2_MAX_NUM_SAMPLE_POINTS = 30000000
GLYPH2_SEED = 10333
SHOW_VEL_LUT_COLOR_BAR = False
VEL_LUT_COLORBAR_ORIENTATION = 'Vertical'
VEL_LUT_COLORBAR_WINDOW_LOCATION = 'AnyLocation'
VEL_LUT_COLORBAR_POSITION = [0.85, 0.65]
VEL_LUT_COLORBAR_LENGTH = 0.3
VIEW_SIZE = [1900, 1200]
REDUCE_POWER = 0.4
